name: "Menu Creation"
description: "Creates the website menu after the convert workflow is run"
author: "emanuel-lima@outlook.com"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "server"
  color: "green"
